[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
nanoid = "*"
numpy = "*"
svgwrite = "*"
scipy = "*"
bs4 = "*"
fastapi = {extras = ["all"], version = "*"}
starlette = "*"
typing-extensions = "*"
# This causes a very obscure error due to
# https://github.com/pypa/pipenv/issues/4900
# chaintrap-maptool = {editable = true, path = "."}

[dev-packages]
pytest = "*"
black = "*"

[requires]
python_version = "3.11"

[scripts]
test = "pytest"
